### ISSUE TITLE
Using on CI4

### ISSUE THREAD

**Issue by mrelliot69** [lonnieezell/codeigniter-shield#34]
Heyy @lonnieezell , i hope everything is good. 
I'm starting a new project and wanted to know if this a replacement package of myth auth for ci4 and also if you think its ready for being used in production projects or if still have bugs that need to be fixed

**Comment by lonnieezell** [comment]
I can't promise no bugs, but yes I believe it's ready for production. I know a couple of others have started using it already, and I'm getting things cleaned up for a 1.0 release.

**Comment by mrelliot69** [comment]
sounds good, thanks for the fast answer. any eta on the 1.0 release ? also what is the key difference between shield and the myth auth package that you also develop?

**Comment by lonnieezell** [comment]
Expect the 1.0 in the next week or two. I think it's good now, but want to run back through things a little and see if anything needs to be done for the access tokens. It's been a while but there's something nagging me that more should be there. Oh - and I need to get my taxes done. Not related - but will eat up free time this week. 

For the differences, I think this post sums up some of the bigger differences: https://www.patreon.com/posts/shield-auth-64914665
