### ISSUE TITLE
Identity or Identifier ?

### ISSUE THREAD

**Issue by kenjis** [lonnieezell/codeigniter-shield#70]
> User accounts are stored separately from the information needed to identify that user. These identifying pieces of data we call **User Identifiers**.
https://github.com/lonnieezell/codeigniter-shield/blob/develop/docs/1%20-%20concepts.md#identities

But the tile is `Identities`.
And the classname is `UserIdentity`.
https://github.com/lonnieezell/codeigniter-shield/blob/develop/src/Entities/UserIdentity.php

**Comment by lonnieezell** [comment]
Yes, should be User Identities.
